version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Create Scratch Org
          command: . build/create-scratch-org.sh
      - run:
          name: Validate Components & Run Tests
          command: . build/test.sh
      - store_test_results:
          path: test-results
  deploy-prod:
    docker:
    - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Login to Production
          command: . build/setup-prod.sh
      - run:
          name: Deploy to Production
          command: . build/deploy-prod.sh
  deploy-uat:
    docker:
    - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Login to Production
          command: . build/setup-uat.sh
      - run:
          name: Deploy to Production
          command: . build/deploy-uat.sh
  deploy-qa:
    docker:
    - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Login to Production
          command: . build/setup-qa.sh
      - run:
          name: Deploy to Production
          command: . build/deploy-qa.sh
  deploy-dev:
    docker:
    - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Login to Production
          command: . build/setup-dev.sh
      - run:
          name: Deploy to Production
          command: . build/deploy-dev.sh
workflows:
  version: 2
  validate:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - main
                - uatSandbox
                - qaSandbox
                - devSandbox
      - deploy-prod:
          filters:
            branches:
              only:
                - main
      - deploy-uat:
          filters:
            branches:
              only:
                - uatSandbox
      - deploy-qa:
          filters:
            branches:
              only:
                - qaSandbox
      - deploy-dev:
          filters:
            branches:
              only:
                - devSandbox
